#include <jni.h>
#include <string>
#include <android/log.h>
#include <fstream>
#include <sstream>
#include "external/sha256/sha256.h"

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, "AZURA_INTEGRITY", __VA_ARGS__)

// Declare verifyHash (implemented in native_integrity.cpp)
extern bool verifyHash(const std::string& soPath, uint8_t xorKey);

// XOR‑encrypted SHA256 hash generated by your Python script
const uint8_t ENCRYPTED_EXPECTED_HASH[32] = {
    0x6d, 0x86, 0x5d, 0x11, 0x84, 0x8a, 0xd8, 0xb4,
    0x96, 0xc4, 0xf3, 0xac, 0x75, 0x89, 0x3c, 0x53,
    0x34, 0x16, 0xe6, 0x31, 0xb1, 0x49, 0xa4, 0x4c,
    0xd7, 0x71, 0xd2, 0xdc, 0xd5, 0x4e, 0x70, 0x76,
};

// Commented out duplicates—definitions live in native_integrity.cpp
// #include <iomanip>
// std::string toHex(const uint8_t* data, size_t len) { … }
// bool verifyHash(const std::string& soPath, uint8_t xorKey) { … }

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_azura_protect_NativeIntegrity_checkAppIntegrity(
    JNIEnv *env, jobject thiz, jobject context, jstring key
) {
    // Retrieve the directory where your .so is stored
    jclass contextCls = env->GetObjectClass(context);
    jmethodID getAppInfo = env->GetMethodID(contextCls,
        "getApplicationInfo",
        "()Landroid/content/pm/ApplicationInfo;");
    jobject appInfo = env->CallObjectMethod(context, getAppInfo);
    jclass appInfoCls = env->GetObjectClass(appInfo);
    jfieldID libDirField = env->GetFieldID(appInfoCls,
        "nativeLibraryDir",
        "Ljava/lang/String;");
    jstring libDirJStr = (jstring)env->GetObjectField(appInfo, libDirField);

    const char *libDir = env->GetStringUTFChars(libDirJStr, nullptr);
    std::string fullPath = std::string(libDir)
        + "/libazura_face_lib.so";
    env->ReleaseStringUTFChars(libDirJStr, libDir);

    // Convert the hex key string into a byte
    const char *keyStr = env->GetStringUTFChars(key, nullptr);
    uint8_t xorKey = static_cast<uint8_t>(
        strtol(keyStr, nullptr, 16));
    env->ReleaseStringUTFChars(key, keyStr);

    // Call the shared implementation
    return verifyHash(fullPath, xorKey)
        ? JNI_TRUE
        : JNI_FALSE;
}
